site_name: OuterSpace Operator
site_url: https://operator.outerspace.sh
site_author: Ludovic FERNANDEZ, Alien6
site_description: >-
  OuterSpace Operator is a robust tool designed to efficiently manage, deploy and operate your algorithms on Kubernetes.
  Install and configure OuterSpace Operator thanks to our comprehensive documentation.

# Repository
repo_name: alien6-studio/outerspace-operator
repo_url: https://github.com/alien6-studio/outerspace-operator

# Copyright
copyright: Copyright &copy; 2023 Alien6

theme:
  name: material
  custom_dir: overrides
  logo: assets/images/logo.png
  icon:
    repo: fontawesome/brands/github-alt 
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/images/logo.png
  features:
    - announce.dismiss
    - announce.hide
    # - content.action.edit
    # - content.action.view
    # - content.code.annotate
    - content.code.copy
    # - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    #- toc.integrate
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - social:
      cards_dir: assets/images/social
  - blog:
      archive: false
      #blog_toc: true  
      blog_dir: blog
      post_readtime: true
      post_readtime_words_per_minute: 280


extra:
  generator: false
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    actions:
      - accept
  analytics:
    provider: google
    property: G-LG6R0GSCH8
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/heart 
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/heart-broken
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by contacting our 
            support team using Live Chat.

extra_css:
  - assets/stylesheets/extra.css

# Page tree
nav:
  - Home: index.md
  - Getting Started:
    - Introduction: introduction.md
    - Key Usages: key-usages.md
    - Key Features: 
      - Features: features/features.md
      - Ground Control: features/ground-control.md
    - Setup:
      - Installation Guide: setup/installation-guide.md
      - Configuration Guide: setup/configuration-guide.md
      - Security Guide: setup/security-guide.md
  - Insiders:
    - Program: insiders/index.md
    - Roadmap: insiders/roadmap.md
  - About:
    - FAQ: about/faq.md
    - Commercial Support: about/commercial-support.md
    - Enterprise Support: about/enterprise-support.md
    - Press Room: about/press-room.md
  - Blog:
    - blog/index.md

